'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';import {Shell,BookingForm,RoomCard,GalleryGrid} from './components';import {rooms,offers,gallery} from './data';
const slides=[
{eyebrow:'ROYAL BELGIUM HOTEL & SUITES49',title:'A refined Brussels stay, made effortless.',text:'Modern comfort, warm hospitality and a direct booking experience designed around the way you travel.',image:'https://images.unsplash.com/photo-1566665797739-1674de7a421a?auto=format&fit=crop&w=1800&q=88'},
{eyebrow:'ROOMS & SUITES',title:'Space to slow down and settle in.',text:'Discover elegant rooms and suites with thoughtful details for leisure, business and special city breaks.',image:'Public/images/img022-2399x1600.jpeg'},
{eyebrow:'ROYAL BELGIUM HOTEL & SUITES',title:'A refined Brussels stay, made effortless.',text:'Modern comfort, warm hospitality and a direct booking experience designed around the way you travel.',image:'Public/images/img033-1684x1600.jpeg'},
{eyebrow:'YOUR BRUSSELS BASE',title:'Stay close to what makes the city special.',text:'Use the hotel as your comfortable starting point for culture, dining, shopping and Belgian discoveries.',image:'Public/images/img044-1600x1600.jpeg'}];
export default function Home(){const [active,setActive]=useState(0);useEffect(()=>{const t=setInterval(()=>setActive(v=>(v+1)%slides.length),6500);return()=>clearInterval(t)},[]);return <Shell><main><section className="hero"><div className="hero-slides">{slides.map((s,i)=><div key={s.title} className={'hero-slide '+(i===active?'active':'')} style={{backgroundImage:`url(${s.image})`}}><div className="wrap hero-inner"><span className="eyebrow">{s.eyebrow}</span><h1>{s.title}</h1><p>{s.text}</p><div className="actions"><Link href="/book" className="gold-btn">Book your stay <span>→</span></Link><Link href="/rooms" className="outline-btn">Explore rooms <span>→</span></Link></div></div></div>)}</div><div className="hero-slide-count"><span>{String(active+1).padStart(2,'0')}</span><i>/</i><span>{String(slides.length).padStart(2,'0')}</span></div><div className="hero-nav"><button onClick={()=>setActive((active-1+slides.length)%slides.length)}>←</button><button onClick={()=>setActive((active+1)%slides.length)}>→</button><div>{slides.map((s,i)=><button key={s.title} className={i===active?'dot active':'dot'} onClick={()=>setActive(i)} aria-label={'Slide '+(i+1)}></button>)}</div></div></section><div className="booking-float"><BookingForm/></div>
<section className="section"><div className="section-intro center"><span className="eyebrow">ROOMS &amp; SUITES</span><h2>Stay beautifully.</h2><p>Choose from elegant rooms and suites designed for restful nights, productive mornings and memorable Brussels stays.</p></div><div className="room-grid">{rooms.map(r=><RoomCard key={r.slug} room={r}/>)}</div><div className="center section-action"><Link className="dark-btn" href="/rooms">View all rooms <span>→</span></Link></div></section>
<section className="experience"><div className="experience-img" style={{backgroundImage:`url(${gallery[1]})`}}></div><div className="experience-copy"><span className="eyebrow">THE HOTEL EXPERIENCE</span><h2>Everything you need, beautifully considered.</h2><p>From breakfast and dining to wellness, meetings, local recommendations and guest support, our services are shaped around a comfortable city stay.</p><div className="mini-grid"><div><b>24/7</b><span>Reception</span></div><div><b>Fast</b><span>Wi-Fi</span></div><div><b>Daily</b><span>Breakfast</span></div><div><b>Local</b><span>Guidance</span></div></div><Link className="gold-btn" href="/facilities">Discover facilities <span>→</span></Link></div></section>
<section className="section"><div className="section-intro center"><span className="eyebrow">SPECIAL OFFERS</span><h2>More reasons to stay.</h2><p>Curated packages for romantic escapes, weekends and business travel.</p></div><div className="offer-grid">{offers.map(o=><article className="offer-card" key={o.title} style={{backgroundImage:`linear-gradient(180deg,transparent 20%,rgba(0,0,0,.85)),url(${o.image})`}}><div><span className="eyebrow">FROM {o.price}</span><h3>{o.title}</h3><p>{o.text}</p><Link className="gold-btn" href="/book">Reserve <span>→</span></Link></div></article>)}</div></section>
<section className="location-band"><div className="wrap location-copy"><span className="eyebrow">BELGIUM, YOUR WAY</span><h2>Explore Brussels beyond the hotel.</h2><p>Historic landmarks, museums, shopping, restaurants and local experiences are all part of the stay.</p><Link className="gold-btn" href="/location">Explore Brussels <span>→</span></Link></div><div className="location-img" style={{backgroundImage:`url(${gallery[5]})`}}></div></section>
<section className="section"><div className="section-intro center"><span className="eyebrow">A GLIMPSE INSIDE</span><h2>Designed for memorable stays.</h2></div><GalleryGrid items={gallery.slice(0,6)}/></section>
<section className="trust"><div className="wrap trust-grid"><div><span className="eyebrow">WHY ROYAL BELGIUM</span><h2>The details make the difference.</h2></div><div><p>Simple booking. Thoughtful spaces. Helpful people. A Brussels stay that feels polished without feeling complicated.</p><Link href="/about" className="text-link">Discover our story <b>→</b></Link></div></div></section>
</main></Shell>}
